### ISSUE TITLE
dcor requires Python '>=2.7, >=3.5, <4' but the running Python is 2.7.14

### ISSUE THREAD

**Issue by zihaozhu93** [vnmabus/dcor#1]
hi, is this weird when i `pip install docr` but failed

**Comment by vnmabus** [comment]
I assume that you mean `pip install dcor`. Can you provide a description of the error?

**Comment by vnmabus** [comment]
The problem should be solved now. Thank you for bringing up the issue. Don't hesitate to open another issue if you have another problem!
