### ISSUE TITLE
add support for faster dcor

### ISSUE THREAD

**Issue by satra** [vnmabus/dcor#14]
in this paper: https://arxiv.org/pdf/1810.11332.pdf an `O(n log n)` version of the algorithm is reported. it may be worthwhile to recode into python.

**Comment by satra** [comment]
never mind. just saw that this was already implemented in #8.

**Comment by vnmabus** [comment]
Yes, you can access this functionality using the argument `method='MERGESORT'`. In https://dcor.readthedocs.io/en/latest/performance.html I compare its performance against the naive algorithm and the other fast method (AVL). Although in the generated documentation appears to beat both methods, in my computer its performance is similar to AVL, and I am not sure why.

I will probably update the algorithm to use MERGESORT by default if possible, as it does not seem to perform worse than AVL and in some machines performs better.

**Comment by satra** [comment]
thank you @vnmabus
