### ISSUE TITLE
Exponent implementation question

### ISSUE THREAD

**Issue by TMiguelT** [vnmabus/dcor#24]
Hi again. I wondered if you could explain the logic here: https://github.com/vnmabus/dcor/blob/161a6f5928ec0f30ce89fcfd5e90e6ed9315e383/dcor/distances.py#L56-L57
If, for example, we set `exponent=2`, which should test for mean differences only (James & Matteson, 2015), it seems that this line would raise the distance to the power of 1, making it equivalent to `exponent=1`. Is this correct, or am I misunderstanding something?

Thanks!

**Comment by vnmabus** [comment]
If you look at lines 51-52, when `exponent` is not 1, the distance computed is the square of the euclidean distance, so the exponent must be divided by 2 to compensate:

https://github.com/vnmabus/dcor/blob/161a6f5928ec0f30ce89fcfd5e90e6ed9315e383/dcor/distances.py#L51-L52

**Comment by TMiguelT** [comment]
Ah, I didn't appreciate what that meant. Thanks!
