### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\domin\\PycharmProjects\\Trading_Backtesting_ML\\venv\\lib\\site-packages\\dcor\\__pycache__\\_fast_dcov_mergesort._generate_distance_covariance_sqr_mergesort_generic_impl.locals._distance_covariance_sqr_mergesort_generic_impl-163.py38.nbi.tmp.4ae6be2f415b45ff'

### ISSUE THREAD

**Issue by DominicHJ45** [vnmabus/dcor#39]
Cannot import dcor as for some reason the __pycache__ folder seems to be missing something

**Comment by vnmabus** [comment]
I think this is the same problem as https://github.com/GAA-UAM/scikit-fda/issues/482.

Please try the solutions mentioned in https://github.com/GAA-UAM/scikit-fda/issues/482#issuecomment-1276024989 and tell me if they work for you.

**Comment by DominicHJ45** [comment]
Thank you this helped solve the problem!
