### ISSUE TITLE
Question about the shape of the input array

### ISSUE THREAD

**Issue by Sunflowerbeaut** [vnmabus/dcor#50]
I have created an autoencoder as a feature extractor. To make the output of the encoder as independent as possible from the input. I chose dcor as an additional loss to train the autoencoder. However, I have some problems when calculating the dcor loss. 
The input shape of the batch data is [32, 1, 28, 14] and the embedding shape is [32, 8, 14, 7]. But it seems that the calculation cannot be performed directly. The Error part is as follows:
![image](https://user-images.githubusercontent.com/106635456/222753639-ee897f9c-5af6-4110-9a40-4a50661f4a98.png)

I wonder if there have some way to calculate the dcor loss of the input and the embedding. Hope to get your answer :)

**Comment by vnmabus** [comment]
What `distance_correlation` expects is two matrices N x P, and N x Q with N the number of observations and P and Q the dimensions of the two random vectors.

Depending on what your dimensions mean, you want to reshape the tensor to put them as part of one of these two categories, or to compute `distance_correlation` several times (you could use `rowwise` in this case).

**Comment by vnmabus** [comment]
Were you able to fix your problem?

**Comment by Sunflowerbeaut** [comment]
Thank you for your response. I have conducted experiments on MNIST dataset, but the distance correlation hardly changed. Anyway, thank you again! Hope you have a wonderful day.
