### ISSUE TITLE
Can distance correlation-based t test is theoretically correct to implement for "uni"-dimensional data?

### ISSUE THREAD

**Issue by Palash123-4** [vnmabus/dcor#52]
The whole t-test is based on the idea that the dimensions of X and Y must be high. What do you think about that?

**Comment by vnmabus** [comment]
Yes, that is true. It is mentioned in the [docstring](https://dcor.readthedocs.io/en/latest/functions/dcor.independence.distance_correlation_t_test.html#dcor.independence.distance_correlation_t_test):

"Test of independence for **high dimension**."

Moreover, the [example](https://dcor.readthedocs.io/en/latest/auto_examples/plot_dcor_t_test.html#sphx-glr-auto-examples-plot-dcor-t-test-py) also expands on that:

"The test illustrated here is an asymptotic test, that relies in the approximation of the statistic distribution to the Student’s t-distribution under the null hypothesis, **when the dimension of the data goes to infinity**. This test is thus faster than permutation tests, as it does not require the use of permutations of the data, and it is also deterministic for a given dataset. However, the test **should be applied only for high-dimensional data**, at least in theory."

**Comment by Palash123-4** [comment]
Thanks for your response.
Luckily, I found a univariate version test also based on distance correlation in "https://www.tandfonline.com/doi/epdf/10.1080/10618600.2021.1938585?needAccess=true&role=button".
