### ISSUE TITLE
Range of distance correlation

### ISSUE THREAD

**Issue by AbhiPawar5** [vnmabus/dcor#64]
### Bug description summary

Hi team, thank you for creating and maintaining dcor, I have found this extremely easy to use.

My question is - What is the range of dcor? I see values beyond 1.0. 

### Code to reproduce the bug

```Python
def distance_correlation(df):
    # Filter df to select numerical columns only
    numerical_cols = df.select_dtypes(include=['number']).columns
    correlations = {}

    for col1, col2 in combinations(numerical_cols, 2):
        dist_corr = dcor.distance_correlation(df[col1].values, df[col2].values)
        correlations[(col1, col2)] = dist_corr
                
    return correlations
```

### Expected result

The correlation range between 0 and 1.

### Actual result

When I pass my dataframe, I see one of the values of dcor as 1.393317

### Software versions

dcor==0.6
MacOs : 12.5.1

**Comment by AbhiPawar5** [comment]
Hi @vnmabus, I wish I could but it is one of our internal demo datasets. Sorry.
But I can share that this correlation of 1.39 occurs on CUSTOMER_ID and ACCOUNT_NUMBER which have unique 1:1 mapping.

**Comment by vnmabus** [comment]
In that case, the dcor should be 1.
How many samples do you have?
Can you reproduce the error by altering the dataset? What happens if you reduce the number of samples or change their values? Can you find a shareable set in which the problem is still present?

**Comment by AbhiPawar5** [comment]
Yes, I was under the same impression that dcor should be 1. Here's the dataset attached.
Can you please take a look?

[DEMO1.profiles_data.sample_data copy.csv](https://github.com/vnmabus/dcor/files/15319376/DEMO1.profiles_data.sample_data.copy.csv)

**Comment by vnmabus** [comment]
I cannot reproduce it in the current `develop` version:
```python
import numpy as np
import dcor

a = np.loadtxt("DEMO1.profiles_data.sample_data.copy.csv", skiprows=1, delimiter=",", usecols=(0, 1))

dcor.distance_correlation(a[:, 0], a[:, 1])
```
```
0.03820843330489932
```

Please, check if this code has the same results in your machine, with your installed dcor version. If not, please try also with the develop version. Maybe it is just some bug fixed but not yet released.

**Comment by AbhiPawar5** [comment]
Yes, I see the similar result as yours `0.0382084333048913`
BUT, if you do
```
a = np.loadtxt("DEMO1.profiles_data.sample_data.copy.csv", skiprows=1, delimiter=",", usecols=(0, 1))
dcor.distance_correlation(df['ACCOUNTNUMBER'].values, df['CUSTOMERID'].values)
```
you will see `1.3933173158759997 `

It has something to do when we pass dataframe?!

**Comment by vnmabus** [comment]
You are not really passing a dataframe (you are calling `values`, obtaining the internal NumPy array instead). Could you compare the values of `(df['ACCOUNTNUMBER'].values, df['CUSTOMERID'].values)` with the ones in `(a[:, 0], a[:, 1])`? Maybe the dtype differs, or something like that?

**Comment by AbhiPawar5** [comment]
Found the issue. We get different results depending on the datatype of individual array elements.
If you add the following line to your code shared above, you can get dcor greater than 1.0
```
a = a.astype(int)
```

**Comment by vnmabus** [comment]
Then it may be related with #59. That is fixed (at least partially) in the develop version, and indeed it works on my machine. In any case, it is better to cast them to float, as that is the optimized path.

**Comment by AbhiPawar5** [comment]
I understand that casting them to float is optimised for operations but the results are very apart! 0.038 vs 1.39 just because of change in data types is what I didn't understand fully.

Then the question is - Which result should I trust? `0.038` or `1.39`?

**Comment by vnmabus** [comment]
0.038 is the right one. The other may be because of an overflow in the intermediate computations, which does not happen in current develop.
