### ISSUE TITLE
Causes segmentation fault

### ISSUE THREAD

**Issue by mnowotnik** [vnmabus/dcor#7]
In conda-based virtualenv python 3.7.2 importing dcor into project
causes crash with segmentation fault error for me.

**Comment by vnmabus** [comment]
I can not reproduce the crash in Windows. I will try in Linux when I have time. Can you provide a more detailed description of your environment?

**Comment by vnmabus** [comment]
I can not reproduce the crash in Linux either. Are you downloading dcor from pip or conda? What is your dcor version? Can you reexecute with valgrind, or look at the core dump in order to see where the crash happen? Thank you in advance.

**Comment by mnowotnik** [comment]
Sure, I'll post some info later.

**Comment by mnowotnik** [comment]
It might have been issue of improper usage. Cannot reproduce.
